apiVersion: v1
kind: Secret
metadata:
  name: thoughts-secrets
type: Opaque
stringData:
  # NOTE: These are example values. Replace with actual secrets in production
  # Consider using sealed-secrets or external secret management
  mongodb-uri: "mongodb://mongo-thoughts:27017/aurora_thoughts"

