apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
type: Opaque
stringData:
  # NOTE: These are example values. Replace with actual secrets in production
  # Consider using sealed-secrets or external secret management
  database-url: "postgresql://aurora:aurora_password@postgres-identity:5432/aurora_identity"
  jwt-secret: "your-secret-key-change-this-in-production"

